name = "tracker-lists"
main = "src/index.js"
compatibility_date = "2025-01-01"

# Created by `wrangler kv namespace create LISTS` — paste the printed id here.
# See DEPLOY.md.
[[kv_namespaces]]
binding = "LISTS"
id = "358f0e0138db4a6a91aa05316ac3c5c7"
